server:
  port: 10000
endpoints: 
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
management:
  security:
    enabled: false
eureka:
  server:
    enable-self-preservation: false       
    eviction-interval-timer-in-ms: 6000000   
  client:
    registerWithEureka: false  
    fetchRegistry: false   
    serviceUrl: 
       defaultZone: http://127.0.0.1:${server.port}/eureka/